name: Deploy to Render

on:
  push:
    branches:
      - main   # deploy when pushing to main branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Render
        run: echo "${{ secrets.RENDER_API_KEY }}" | docker login registry.render.com --username _ --password-stdin

      - name: Build and Push Docker Image
        run: |
          docker build -t registry.render.com/${{ secrets.RENDER_SERVICE_ID }}/flask-docker-app:latest .
          docker push registry.render.com/${{ secrets.RENDER_SERVICE_ID }}/flask-docker-app:latest

      - name: Trigger Deploy on Render
        run: |
          curl -X POST \
          -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}" \
          -H "Content-Type: application/json" \
          -d '{"clearCache": false}' \
          https://api.render.com/v1/services/${{ secrets.RENDER_SERVICE_ID }}/deploys
